[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
bagsvault = "AXEc2HCqETrPqzdG8AkErLxfNXDHyeH4cwykvX6qxXvJ"

[programs.devnet]
bagsvault = "AXEc2HCqETrPqzdG8AkErLxfNXDHyeH4cwykvX6qxXvJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'No JS tests — run cargo test inside programs/bagsvault'"

[workspace]
members = ["programs/bagsvault"]
